from fpdf import FPDF
from datetime import datetime

def generate_pdf_report(source_type, summary, insights_text):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_margins(20, 20, 20)
    pdf.set_auto_page_break(auto=True, margin=20)

    # Header
    pdf.set_fill_color(108, 99, 255)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 12, f"Automated {source_type.title()} Report",
        ln=True, fill=True, align="C")

    pdf.set_text_color(120, 120, 120)
    pdf.set_font("Helvetica", size=9)
    pdf.cell(0, 7,
        f"Generated: {datetime.now().strftime('%B %d, %Y at %H:%M')}",
        ln=True, align="C")
    pdf.ln(5)

    # Key metrics section
    pdf.set_fill_color(240, 239, 255)
    pdf.set_text_color(26, 26, 46)
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 8, "Key Metrics", ln=True, fill=True)
    pdf.ln(2)

    pdf.set_font("Helvetica", size=9)
    pdf.set_text_color(60, 60, 60)

    page_width = pdf.w - 2 * pdf.l_margin

    for key, value in summary.items():
        if key == "columns_detected":
            continue
        label = key.replace("_", " ").title()
        # Convert value to clean string
        raw = str(value)
        # Truncate very long values
        if len(raw) > 120:
            raw = raw[:120] + "..."
        line = f"{label}: {raw}"
        # Word wrap the line
        words = line.split(" ")
        current = ""
        for word in words:
            test = current + " " + word if current else word
            if pdf.get_string_width(test) <= page_width:
                current = test
            else:
                if current:
                    pdf.cell(0, 6, current, ln=True)
                current = word
        if current:
            pdf.cell(0, 6, current, ln=True)

    pdf.ln(5)

    # AI insights section
    pdf.set_fill_color(26, 26, 46)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 8, "AI-Generated Executive Summary",
        ln=True, fill=True)
    pdf.ln(3)

    # Clean special characters
    clean = (
        insights_text
        .replace("\u2022", "-")
        .replace("\u2019", "'")
        .replace("\u2018", "'")
        .replace("\u201c", '"')
        .replace("\u201d", '"')
        .replace("\u2013", "-")
        .replace("\u2014", "-")
        .replace("\u2192", "->")
        .replace("\u2190", "<-")
        .replace("**", "")
        .replace("##", "")
        .replace("#", "")
        .replace("*", "-")
        .encode("ascii", "ignore")
        .decode("ascii")
    )

    pdf.set_text_color(50, 50, 50)
    pdf.set_font("Helvetica", size=9)

    for line in clean.split("\n"):
        line = line.strip()
        if line == "":
            pdf.ln(3)
            continue
        # Word wrap every line
        words = line.split(" ")
        current = ""
        for word in words:
            test = current + " " + word if current else word
            if pdf.get_string_width(test) <= page_width:
                current = test
            else:
                if current:
                    pdf.cell(0, 5, current, ln=True)
                # Handle single word longer than page
                if pdf.get_string_width(word) > page_width:
                    while len(word) > 0:
                        for i in range(len(word), 0, -1):
                            if pdf.get_string_width(word[:i]) <= page_width:
                                pdf.cell(0, 5, word[:i], ln=True)
                                word = word[i:]
                                break
                    current = ""
                else:
                    current = word
        if current:
            pdf.cell(0, 5, current, ln=True)

    pdf.ln(6)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(160, 160, 160)
    pdf.cell(0, 5,
        "Auto-generated by AI Reporting Pipeline | For review purposes only",
        ln=True, align="C")

    return bytes(pdf.output())